version: 0.2

phases:

  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 998105437962.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build Docker image
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 998105437962.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo Push Docker image to ECR
      - docker push 998105437962.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
